<a href="https://colab.research.google.com/github/ankit071105/Machine-Learning-/blob/main/Feature-Engineering/Categorical-Encoding%20/ordinal-encoding/ordinal_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd

In [14]:

df = pd.read_csv('customer.csv')

In [15]:

df.sample(5)

age  gender   review education purchased
42   30  Female     Good        PG       Yes
25   57  Female     Good    School        No
13   57  Female  Average    School        No
28   48    Male     Poor    School        No
32   92    Male  Average        UG       Yes

In [16]:
df = df.iloc[:,1:] # removing age

In [17]:
df.head()

gender   review education purchased
0  Female  Average    School        No
1  Female     Poor        UG        No
2  Female     Good        PG        No
3  Female     Good        PG        No
4  Female  Average        UG        No

In [18]:
df.iloc[:,0:3] # removing purchased col

gender   review education
0   Female  Average    School
1   Female     Poor        UG
2   Female     Good        PG
3   Female     Good        PG
4   Female  Average        UG
5   Female  Average    School
6     Male     Good    School
7   Female     Poor    School
8   Female  Average        UG
9     Male     Good        UG
10  Female     Good        UG
11    Male     Good        UG
12    Male     Poor    School
13  Female  Average    School
14    Male     Poor        PG
15    Male     Poor        UG
16    Male     Poor        UG
17  Female     Poor        UG
18    Male     Good    School
19    Male     Poor        PG
20  Female  Average    School
21    Male  Average        PG
22  Female     Poor        PG
23  Female     Good    School
24  Female  Average        PG
25  Female     Good    School
26  Female     Poor        PG
27  Female     Poor        PG
28    Male     Poor    School
29  Female  Average        UG
30    Male  Average        UG
31  Female     Poor    School
32    Male  Average        UG
33  Female     Good        PG
34    Male  Average    School
35    Male     Poor    School
36  Female     Good        UG
37    Male  Average        PG
38  Female     Good    School
39    Male     Poor        PG
40    Male     Good    School
41    Male     Good        PG
42  Female     Good        PG
43    Male     Poor        PG
44  Female  Average        UG
45    Male     Poor        PG
46  Female     Poor        PG
47  Female     Good        PG
48  Female     Good        UG
49  Female     Good        UG

In [19]:
# applying train_test_split functions to educations and review
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:3], df.iloc[:,-1], test_size=0.2)

In [20]:
X_train

review education
13  Average    School
2      Good        PG
28     Poor    School
19     Poor        PG
41     Good        PG
37  Average        PG
20  Average    School
43     Poor        PG
1      Poor        UG
16     Poor        UG
27     Poor        PG
39     Poor        PG
31     Poor    School
33     Good        PG
46     Poor        PG
45     Poor        PG
21  Average        PG
17     Poor        UG
10     Good        UG
30  Average        UG
14     Poor        PG
47     Good        PG
24  Average        PG
29  Average        UG
12     Poor    School
42     Good        PG
34  Average    School
7      Poor    School
23     Good    School
5   Average    School
49     Good        UG
4   Average        UG
22     Poor        PG
11     Good        UG
26     Poor        PG
3      Good        PG
40     Good    School
36     Good        UG
35     Poor    School
6      Good    School

In [21]:

from sklearn.preprocessing import OrdinalEncoder

In [22]:
X_train

review education
13  Average    School
2      Good        PG
28     Poor    School
19     Poor        PG
41     Good        PG
37  Average        PG
20  Average    School
43     Poor        PG
1      Poor        UG
16     Poor        UG
27     Poor        PG
39     Poor        PG
31     Poor    School
33     Good        PG
46     Poor        PG
45     Poor        PG
21  Average        PG
17     Poor        UG
10     Good        UG
30  Average        UG
14     Poor        PG
47     Good        PG
24  Average        PG
29  Average        UG
12     Poor    School
42     Good        PG
34  Average    School
7      Poor    School
23     Good    School
5   Average    School
49     Good        UG
4   Average        UG
22     Poor        PG
11     Good        UG
26     Poor        PG
3      Good        PG
40     Good    School
36     Good        UG
35     Poor    School
6      Good    School

In [23]:
# add that much list inside list total categorial data transform
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [24]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [25]:
oe.fit_transform(X_train)
oe.fit_transform(X_train)

array([[1., 0.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [2., 0.]])

In [26]:
X_train = oe.transform(X_train)

In [27]:
X_train

array([[1., 0.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [2., 0.]])

In [28]:
oe.categories_ # printing the values present in the list

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [29]:
X_train

array([[1., 0.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [2., 0.]])

In [30]:
# used for only output columns
from sklearn.preprocessing import LabelEncoder

In [31]:
le = LabelEncoder()

In [32]:
le.fit(y_train)

LabelEncoder()

In [33]:
le.classes_ # no-0, yes-1

array(['No', 'Yes'], dtype=object)

In [34]:

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [35]:

y_train

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0])