In [122]:

import numpy as np
import pandas as pd

In [123]:

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [124]:
df = pd.read_csv('covid_toy.csv')

In [125]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [126]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [127]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [128]:
X_train

age  gender  fever   cough       city
28   16    Male  104.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
85   16  Female  103.0    Mild  Bangalore
57   49  Female   99.0  Strong  Bangalore
64   42    Male  104.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
69   73  Female  103.0    Mild      Delhi
9    64  Female  101.0    Mild      Delhi
45   72    Male   99.0    Mild  Bangalore
16   69  Female  103.0    Mild    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

# **Without Column Transformer**

In [129]:
# adding simple imputer to fever col
# filling the missing value with means of the fever column
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [138]:
X_train_fever # priniting after applying the simple imputer technique
# filling the missing value with means of the fever column

array([[104.        ],
       [100.        ],
       [103.        ],
       [ 99.        ],
       [104.        ],
       [100.97222222],
       [101.        ],
       [ 98.        ],
       [100.97222222],
       [103.        ],
       [102.        ],
       [ 99.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [101.        ],
       [100.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.97222222],
       [102.        ],
       [101.        ],
       [101.        ],
       [102.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [100.        ],
       [104.        ],
       [104

In [139]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']]) # giving the rank means mild > Strong
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [140]:
X_train_cough # priniting after applying the  Ordinalencoding technique
# ranking the strong as 1 and mild as 0

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],

In [131]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [141]:
X_train_gender_city  # priniting after applying the  OneHotEncoding technique
# [gender, city ,city , city]

array([[1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],


In [142]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape


(80, 1)

In [143]:
X_train_age # Printing Extracting Age

array([[16],
       [19],
       [16],
       [49],
       [42],
       [75],
       [ 8],
       [26],
       [34],
       [48],
       [74],
       [60],
       [13],
       [69],
       [65],
       [56],
       [19],
       [59],
       [38],
       [19],
       [10],
       [69],
       [24],
       [55],
       [75],
       [17],
       [14],
       [10],
       [25],
       [80],
       [64],
       [81],
       [38],
       [82],
       [68],
       [20],
       [24],
       [49],
       [51],
       [83],
       [22],
       [27],
       [51],
       [ 6],
       [27],
       [64],
       [51],
       [50],
       [65],
       [65],
       [46],
       [14],
       [33],
       [82],
       [60],
       [44],
       [70],
       [71],
       [66],
       [42],
       [19],
       [80],
       [82],
       [54],
       [47],
       [12],
       [23],
       [15],
       [23],
       [18],
       [79],
       [ 5],
       [27],
       [34],
       [71],
       [73],
       [64],

In [133]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [144]:
X_train_transformed
#[Age , Fever , Gender , city1 , city 2 ,city 3 , cough]

array([[ 16.        , 104.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 16.        , 103.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 49.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 42.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 75.        , 100.97222222,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [  8.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 26.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 34.        , 100.97222222,   0.        ,   0.        ,
          0.    

# **# **With Column Transformer****

In [147]:
from sklearn.compose import ColumnTransformer

In [148]:
transformer = ColumnTransformer(transformers=[
    # (transformer name , transformer operator , list of col name )
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')
# passthorugh - will not touch the col
# drop - will remove the col

In [149]:
transformer.fit_transform(X_train)

array([[104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  16.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [100.97222222,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   8.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  26.        ],
       [100.97222222,   1.        ,   0.        ,   0.        ,
          0.    

In [136]:
transformer.fit_transform(X_train).shape

(80, 7)

In [145]:
transformer.transform(X_test)

array([[102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [100.97222222,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.    

In [137]:
transformer.transform(X_test).shape

(20, 7)